# Generated by Django 5.2.9 on 2025-12-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analyzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("model_code", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="hospital",
            old_name="code",
            new_name="serialnumber",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="address",
        ),
        migrations.AddField(
            model_name="hospital",
            name="analyzer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supply.analyzer",
            ),
        ),
    ]
