# Generated by Django 5.2.9 on 2025-12-15 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0002_analyzer_rename_code_hospital_serialnumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="batch_no",
        ),
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="qty_packs",
        ),
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="reagent",
        ),
        migrations.AlterField(
            model_name="hospitaldelivery",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="ReagentDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="supply.hospitaldelivery",
                    ),
                ),
                (
                    "reagent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="supply.reagent"
                    ),
                ),
            ],
        ),
    ]
