# Generated by Django 5.1.5 on 2025-12-25 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0003_remove_hospitaldelivery_batch_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumptionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_months", models.IntegerField(default=3)),
                ("samples_per_day", models.IntegerField()),
                ("diluent_qty", models.FloatField()),
                ("whitediff_qty", models.FloatField()),
                ("cleaner_qty", models.FloatField()),
                ("minoclair_qty", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.hospital",
                    ),
                ),
            ],
        ),
    ]
