# Generated by Django 5.1.5 on 2025-12-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0004_consumptionprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptionrule",
            name="bottle_volume_ml",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumptionrule",
            name="ml_per_sample",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consumptionrule",
            name="reagent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="supply.reagent"
            ),
        ),
    ]
