# Generated by Django 5.1.5 on 2025-12-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0005_consumptionrule_bottle_volume_ml_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumptionrule",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="consumptionrule",
            name="ml_per_test",
        ),
        migrations.RemoveField(
            model_name="consumptionrule",
            name="packs_per_whitediff",
        ),
    ]
