# Generated by Django 5.1.5 on 2025-12-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0006_remove_consumptionrule_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptionrule",
            name="desc",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="consumptionrule",
            name="bottle_volume_ml",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="consumptionrule",
            name="ml_per_sample",
            field=models.FloatField(),
        ),
    ]
