# Generated by Django 5.1.5 on 2025-12-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0007_consumptionrule_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumptionrule",
            name="bottle_volume_ml",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
