# Generated by Django 5.1.5 on 2025-12-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0008_alter_consumptionrule_bottle_volume_ml"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumptionrule",
            name="ml_per_sample",
        ),
        migrations.AddField(
            model_name="consumptionrule",
            name="ml_per_test",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consumptionrule",
            name="reagent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="supply.reagent"
            ),
        ),
    ]
