# Generated by Django 5.1.5 on 2025-12-25 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0009_remove_consumptionrule_ml_per_sample_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumptionrule",
            name="bottle_volume_ml",
        ),
        migrations.RemoveField(
            model_name="consumptionrule",
            name="desc",
        ),
        migrations.AddField(
            model_name="consumptionrule",
            name="ml_per_wash",
            field=models.FloatField(
                blank=True, help_text="Consumption per cleaning wash (ml)", null=True
            ),
        ),
        migrations.AddField(
            model_name="consumptionrule",
            name="washes_per_week",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of washes per week"
            ),
        ),
        migrations.AlterField(
            model_name="consumptionrule",
            name="ml_per_test",
            field=models.FloatField(
                blank=True, help_text="Consumption per blood test (ml)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="consumptionrule",
            name="reagent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="supply.reagent"
            ),
        ),
    ]
