# Generated by Django 5.1.5 on 2025-12-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0010_remove_consumptionrule_bottle_volume_ml_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehousestock",
            name="quantity_ml",
        ),
        migrations.AlterField(
            model_name="warehousestock",
            name="quantity_packs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="warehousestock",
            name="reagent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="supply.reagent"
            ),
        ),
    ]
