# Generated by Django 5.1.5 on 2025-12-25 11:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0011_remove_warehousestock_quantity_ml_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="date",
        ),
        migrations.AddField(
            model_name="hospitaldelivery",
            name="delivered_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospitaldelivery",
            name="quantity_packs",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospitaldelivery",
            name="reagent",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="supply.reagent",
            ),
            preserve_default=False,
        ),
    ]
