# Generated by Django 5.1.5 on 2026-01-08 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0012_remove_hospitaldelivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaldelivery",
            name="reagent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supply.reagent",
            ),
        ),
        migrations.DeleteModel(
            name="ReagentDeliveryItem",
        ),
    ]
