# Generated by Django 5.1.5 on 2026-01-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0013_alter_hospitaldelivery_reagent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="quantity_packs",
        ),
        migrations.RemoveField(
            model_name="hospitaldelivery",
            name="reagent",
        ),
        migrations.AddField(
            model_name="hospitaldelivery",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="HospitalDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_packs", models.PositiveIntegerField()),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="supply.hospitaldelivery",
                    ),
                ),
                (
                    "reagent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="supply.reagent"
                    ),
                ),
            ],
        ),
    ]
