# Generated by Django 5.1.5 on 2026-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0014_remove_hospitaldelivery_quantity_packs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="name_analyser",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
