# Generated by Django 5.1.5 on 2026-01-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0015_hospital_name_analyser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="analyzer",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="name_analyser",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="serialnumber",
        ),
        migrations.CreateModel(
            name="HospitalAnalyzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "analyzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.analyzer",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.hospital",
                    ),
                ),
            ],
            options={
                "unique_together": {("hospital", "serial_number")},
            },
        ),
    ]
