# Generated by Django 5.1.5 on 2026-02-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0016_remove_hospital_analyzer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("IN", "Stock In"), ("OUT", "Stock Out")], max_length=3
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "reagent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="supply.reagent"
                    ),
                ),
            ],
        ),
    ]
